#!/usr/bin/env python3
"""Vendor the three webfonts so the site makes no third-party requests.

    python3 fonts.py

Asks Google for the CSS it would serve a modern browser, keeps the latin and
latin-ext subsets, downloads those woff2 files into docs/fonts/, and writes
fonts.css with the URLs rewritten to local paths. build.py inlines that CSS
into the page, so the built site never touches fonts.googleapis.com.

Newsreader, Caveat and Inter are all SIL Open Font License 1.1, which permits
redistribution. docs/fonts/OFL.txt records that.

Re-run only when the font stack changes. The downloaded files are committed.
"""
import pathlib, re, sys, urllib.request

HERE = pathlib.Path(__file__).parent
OUT = HERE / "docs" / "fonts"
CSS_OUT = HERE / "fonts.css"

# Matches the families and axes the page actually uses.
API = ("https://fonts.googleapis.com/css2"
       "?family=Newsreader:ital,opsz,wght@0,6..72,400..500;1,6..72,400..500"
       "&family=Caveat:wght@500..600"
       "&family=Inter:wght@400..600"
       "&display=swap")

# Without a browser UA, Google serves legacy truetype instead of variable woff2.
UA = ("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/124.0 Safari/537.36")

KEEP = ("latin", "latin-ext")

NOTICE = """The woff2 files in this directory are redistributed under the
SIL Open Font License 1.1, which permits bundling and redistribution.

  Newsreader  Production Type          https://fonts.google.com/specimen/Newsreader
  Caveat      Impallari Type           https://fonts.google.com/specimen/Caveat
  Inter       Rasmus Andersson         https://fonts.google.com/specimen/Inter

Full licence text: https://openfontlicense.org/
Regenerate with: python3 fonts.py
"""


def get(url):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read()


def main():
    try:
        css = get(API).decode("utf-8")
    except Exception as e:
        sys.exit("could not reach fonts.googleapis.com: %s" % e)

    blocks = re.findall(r"/\* ([a-z-]+) \*/\s*(@font-face \{.*?\})", css, re.S)
    blocks = [(sub, b) for sub, b in blocks if sub in KEEP]
    if not blocks:
        sys.exit("no latin subsets in the response — did the CSS API change?")

    OUT.mkdir(parents=True, exist_ok=True)
    out, total = [], 0

    for sub, block in blocks:
        fam = re.search(r"font-family: '([^']+)'", block).group(1)
        style = re.search(r"font-style: (\w+)", block).group(1)
        url = re.search(r"url\((https[^)]+)\)", block).group(1)

        name = "%s-%s-%s.woff2" % (fam.lower(), style, sub)
        data = get(url)
        (OUT / name).write_bytes(data)
        total += len(data)

        out.append(re.sub(r"url\(https[^)]+\)", "url(fonts/%s)" % name, block)
                   .replace("@font-face {", "@font-face{"))
        print("  %-34s %5.1f KB" % (name, len(data) / 1024))

    (OUT / "OFL.txt").write_text(NOTICE, encoding="utf-8")
    CSS_OUT.write_text(
        "/* Generated by fonts.py — do not edit. Self-hosted; no third-party requests. */\n"
        + "\n".join(out) + "\n", encoding="utf-8")

    print("\nwrote %d faces, %.0f KB total → docs/fonts/" % (len(blocks), total / 1024))
    print("wrote fonts.css (%.1f KB) — build.py inlines this" % (CSS_OUT.stat().st_size / 1024))


if __name__ == "__main__":
    main()
